### ISSUE TITLE
Agent binary download from release S3 bucket fails

### ISSUE THREAD

**Issue by hasanp87** [aws/aws-sagemaker-edge-quick-device-setup#5]
AMD64 setup , after running the setup , following error occurs : 

"2022/01/21 09:29:17 Failed to list objects in bucket sagemaker-edge-release-store-us-west-2-linux-x64 for prefix Releases/. Encountered error operation error S3: ListObjects, https response error StatusCode: 301, RequestID: 09HYVA0T8SMWVJFS, HostID: 5RqUzpFYtB5yoV7ME3DnO+zuH6zHkAxirWI3LMbETiLT/GJBqsgsSlrrZzMploQY9KkRCg8qgNQ=, api error PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint."

**Comment by davidakr** [comment]
#6 should correct this error since the client was limited to the us-west-2 region

**Comment by cnv1989** [comment]
Addressed in new release v0.0.2
